### ISSUE TITLE
project is not running

### ISSUE THREAD

**Issue by Princy9114** [sumansinha0721/GrivoTech_GHCI#1]
when I try to run this project only index.php page is running after clicking on the 'login as -> student' blank page occurs and nothing else happens
![2023-05-17](https://github.com/sumansinha0721/GrivoTech_GHCI/assets/115996250/025a8505-93b7-4d45-bd51-3f90275e0789)
![2023-05-17 (1)](https://github.com/sumansinha0721/GrivoTech_GHCI/assets/115996250/c720b445-36d2-4924-b1f6-5e66c38528c1)

**Comment by sumansinha0721** [comment]
Hi! We made some changes after SIH; I haven't updated them here.
Thank you for bringing this up; I will update them soon. 
BTW here, STUDENT is not working because their higher authority i.e., COLLEGE will add them. So, ignore it for now.
